name: dental_smile
description: Aplicativo de simulação de sorriso
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  share_plus: ^13.3.0
  pdf: ^3.10.7
  printing: ^5.12.0
  open_file: ^3.3.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/


